version: '3.8'

services:
  api_services:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
   
  mysql_db:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: Abc123
      MYSQL_ROOT_PASSWORD: Abc123